export type PublicProductResponse = {
  id: string;
  name: string;
  categoryId: string;
  category?: any;
  brandId: string;
  brand?: any;
  image: string | null;
  subtitle: string;
  overallScore: number;
  isRecommended: boolean;
  price: number;
  currency: string;
  priceLabel: string;
  affiliateLink: null;
  createdAt: Date;
  updatedAt: Date;
  lastUpdated: Date;
  ratings: any[];
  status: string;
};
